### ISSUE TITLE
The docker-compose configuration is not suitable for slow machines

### ISSUE THREAD

**Issue by artrayme** [ostis-apps/nika#5]
**Describe the bug**
The number of container health checks runs out faster than the sc-machine base has time to build 

**To Reproduce**
This can be reproduced on slow hardware or if you reduce the number of health checks in docker-compose 
1. docker compose up --no-build
2. See error "container is unhealthy"

**Expected behavior**
The sc-machine base should be fully built.

**Screenshots**
![docker-health-err](https://user-images.githubusercontent.com/78550819/190229275-73c1bb34-aa77-4308-aa19-85efbcc9bb69.png)

**Desktop (please complete the following information):**
-OS: Manjaro 21.3
- Version: I don't know how to check NIKA's version
- Environment: Nika was run with docker compose (the configuration from this repository was used)

**Additional context**
I just put "20" in the "retries" field in docker-compose and it works fine for me. But maybe you can provide a better solution

**Comment by FallenChromium** [comment]
Thank you for the feedback! It is very important to us, especially at the early stages of development. You're always welcome to ask questions in case you'll encounter any problems :)

Could you please provide your hardware configuration and *estimated* amount of time needed to build KB on your hardware?

It's better to adjust "start period" parameter rather then amount of retries in the Compose file in your situation, because it'd give the server more time to spin up, but after the first successful healthcheck  checks will behave as usual. 20 retries is a bit too much with a 5 second interval, if the server will die, it will take a while for you to see that in the logs.

There's also another way to solve this problem. We have an env variable called `REBUILD_KB` inside our Compose file. If your intention is to use the system mostly in the dialogue mode, you can disable autorebuild and call it manually via `docker compose run machine build` and `docker compose restart` afterwards.

The

**Comment by artrayme** [comment]
The specifications of my computer: 
Processor: Intel core i5 4210u (4 threads, 2.4GHz)
RAM: 8gb
Disk storage: SSD. 
I think these specifications are the most useful. But I can describe in more detail if needed. 

It takes from 90 to 120 seconds to build the base. The build time depends on the background tasks. With the default configuration, the base almost always fails to build, even if there are no background tasks. 

Thanks for the advice to change the value of "start_period". This is really better. I've found my own value -- 100 seconds (other parameters are default values).

**Comment by artrayme** [comment]
And thanks for the information about "REBUILD_KB" flag, it might speed up work with Nika. I think it would be a good idea to mention this flag in README)
